spring:
  application:
    name: Banco Saint Patrick
  datasource:
    url: jdbc:mysql://localhost:3306/bancosaintpatrick
    username: ${dbuser}
    password: ${dbpass}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop